services:
  broken_bulb: # golang db connection issue exception with recovery
    image: 'signaloneai/broken_bulb:dev'
  faulty_roger: # c# application that cannot start properly
    image: 'signaloneai/faulty_roger:dev'
  smoked_server: # nginx server hosting the website with the miss-configuration
    image: 'signaloneai/smoked_server:dev'
    ports:
      - '8082:8082'
  invalid_api_call: # python webserver with bug within one of the endpoints
    image: 'signaloneai/invalid_api_call:dev'
    ports:
      - '5000:5000'
      