services:
  signaloneagent:
    container_name: signaloneagent
    restart: unless-stopped
    image: 'signaloneai/signalone-extension:0.0.1'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "37002:37002"
  signalonefrontend:
    container_name: signalonefrontend
    image: 'signaloneai/signalonefrontend:0.0.1'
    ports:
      - "37001:37001"
    depends_on:
      - signaloneagent
